version: "3"
services:
  backend:
    build:
      context: backend
    restart: unless-stopped
  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    environment:
      - BACKEND_HOSTNAME=backend
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped


