version: "3"
services:
  backend:
    build:
      context: backend
    restart: unless-stopped
  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    environment:
      - BACKEND_HOSTNAME=backend
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
  selenium-firefox:
    image: selenium/standalone-firefox:110.0
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    expose:
      - "4444"
  selenium-usecase:
    build:
      context: selenium
    depends_on:
      - frontend
      - selenium-firefox
    volumes:
      - "~/images:/usr/local/images"

