version: "3"
services:
  backend:
    build: backend/. 
    restart: unless-stopped
  frontend:
    depends_on:
      - backend
    environment:
      - BACKEND_HOSTNAME=backend
    build: frontend/.
    ports:
      - "80:8080"
    restart: unless-stopped
