version: "3"
services:
  backend:
    build:
      context: backend
    restart: unless-stopped
  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    environment:
      - BACKEND_HOSTNAME=backend
    image: bendahl/todo-frontend:2.0
    ports:
      - "80:8080"
    restart: unless-stopped
